# -*- coding: utf-8 -*-
"""Portafolio_backpropagation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLsvIRYot2fQU5cUCrTyTZ6yGbpXFqiX
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

csv_path = "https://raw.githubusercontent.com/a01753010-ui/Portafolio1_Emilio_Torres/main/student_performance_dataset.csv"

df = pd.read_csv(csv_path)

# Features (X) and target (Y)
X = df[['previous_grade', 'study_time_hours']]
Y = df['final_exam_score']

# 70/30 train-test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=20)

X_data = X_train.values  # to NumPy array
Y_data = Y_train.values.reshape(-1, 1)  # to column vector

# Scale X by train max; scale Y being 100 is the max score
X_data = X_data / np.amax(X_data, axis=0)
Y_data = Y_data / 100

class NeuralNetwork(object):
  def __init__(self):
    # parameters
    self.learning_rate = 0.01
    self.inputSize = X_data.shape[1]
    self.outputSize = 1
    self.hiddenSize = 3

    # weights
    self.W1 = np.random.randn(self.inputSize, self.hiddenSize)
    self.W2 = np.random.randn(self.hiddenSize, self.outputSize)

    # biases
    self.b1 = np.zeros((1, self.hiddenSize))
    self.b2 = np.zeros((1, self.outputSize))

  def feedForward(self, X):
    # forward propagation through the network
    self.z = np.dot(X, self.W1) + self.b1
    self.z2 = self.sigmoid(self.z)
    self.z3 = np.dot(self.z2, self.W2) + self.b2
    output = self.sigmoid(self.z3)
    return output

  def sigmoid(self, s, deriv=False):
    if (deriv == True):
      return s * (1-s)
    return 1/(1 + np.exp(-s))

  def backwards(self, X, y, output):
    # backward propagate through the network
    self.output_error = y - output
    self.output_delta = self.output_error * self.sigmoid(output, deriv=True)

    self.z2_error = self.output_delta.dot(self.W2.T)
    self.z2_delta = self.z2_error * self.sigmoid(self.z2, deriv=True)

    self.W1 += X.T.dot(self.z2_delta) * self.learning_rate
    self.W2 += self.z2.T.dot(self.output_delta) * self.learning_rate

    # bias gradients
    self.b1 += np.sum(self.z2_delta, axis=0) * self.learning_rate
    self.b2 += np.sum(self.output_delta, axis=0) * self.learning_rate

  def train(self, X, y):
    output = self.feedForward(X)
    self.backwards(X, y, output)

NN = NeuralNetwork()

for i in range(10000):  # train for 10,000 iterations
  NN.train(X_data, Y_data)

# Scale test data using
X_test_scaled = X_test.values / np.amax(X_train.values, axis=0)
Y_test_scaled = Y_test.values.reshape(-1, 1) / 100

predictions_test_scaled = NN.feedForward(X_test_scaled)

# MSE on test set
loss_test = np.mean(np.square(Y_test_scaled - predictions_test_scaled))

# Error per sample
difference_test_scaled = Y_test_scaled - predictions_test_scaled

# Unscale back to 0-100 for the classification step
Y_test_original = Y_test_scaled * 100
predictions_original = predictions_test_scaled * 100

# Passing threshold
passing_threshold = 70

# Convert to pass/fail binary labels
y_true_binary = (Y_test_original >= passing_threshold).astype(int)
y_pred_binary = (predictions_original >= passing_threshold).astype(int)

# Confusion matrix components
TP = np.sum((y_true_binary == 1) & (y_pred_binary == 1))
TN = np.sum((y_true_binary == 0) & (y_pred_binary == 0))
FP = np.sum((y_true_binary == 0) & (y_pred_binary == 1))
FN = np.sum((y_true_binary == 1) & (y_pred_binary == 0))

# Accuracy
total_samples = len(Y_test_original)
accuracy = (TP + TN) / total_samples

# Recall
recall = TP / (TP + FN)

print(f"Umbral de aprobación: {passing_threshold} puntos")
print(f"Estudiantes reales aprobados: {np.sum(y_true_binary == 1)} de {total_samples}")
print(f"Estudiantes predichos aprobados: {np.sum(y_pred_binary == 1)} de {total_samples}")
print(f"\nTrue Positives (Aprobó y se predijo que aprobó): {TP}")
print(f"True Negatives (Reprobó y se predijo que reprobó): {TN}")
print(f"False Positives (Reprobó pero se predijo que aprobó): {FP}")
print(f"False Negatives (Aprobó pero se predijo que reprobó): {FN}")
print(f"\nMSE: {np.mean(np.square(Y_test_scaled - predictions_test_scaled)):.4f}")
print(f"Accuracy (Precisión general): {accuracy:.2f}")
print(f"Recall (Sensibilidad): {recall:.2f}")

# Confusion matrix
cm = confusion_matrix(y_true_binary, y_pred_binary)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Reprobó (Predicción)', 'Aprobó (Predicción)'],
            yticklabels=['Reprobó (Real)', 'Aprobó (Real)'])
plt.xlabel('Clase Predicha')
plt.ylabel('Clase Real')
plt.title('Matriz de Confusión')
plt.show()